// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBr3Q-hL9q4n2rE2AGZG0GP-zTlXrHAIBE',
    appId: '1:1054840422213:web:9891ec6fce90554cf3c82c',
    messagingSenderId: '1054840422213',
    projectId: 'projectdynamic-c443e',
    authDomain: 'projectdynamic-c443e.firebaseapp.com',
    storageBucket: 'projectdynamic-c443e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDX47FLhG7A4a8q1QOy9pxdlgI5Yp9WXhQ',
    appId: '1:1054840422213:android:3542f07c366db7f8f3c82c',
    messagingSenderId: '1054840422213',
    projectId: 'projectdynamic-c443e',
    storageBucket: 'projectdynamic-c443e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4qGGvR15lTrN5jvUGNQeHpvfRSLZn_X0',
    appId: '1:1054840422213:ios:1ba99c39243ffe76f3c82c',
    messagingSenderId: '1054840422213',
    projectId: 'projectdynamic-c443e',
    storageBucket: 'projectdynamic-c443e.appspot.com',
    iosClientId: '1054840422213-cvkshai2rj5cgnfs513hplq5jh1kmije.apps.googleusercontent.com',
    iosBundleId: 'org.Allee.flutterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4qGGvR15lTrN5jvUGNQeHpvfRSLZn_X0',
    appId: '1:1054840422213:ios:1ba99c39243ffe76f3c82c',
    messagingSenderId: '1054840422213',
    projectId: 'projectdynamic-c443e',
    storageBucket: 'projectdynamic-c443e.appspot.com',
    iosClientId: '1054840422213-cvkshai2rj5cgnfs513hplq5jh1kmije.apps.googleusercontent.com',
    iosBundleId: 'org.Allee.flutterProject',
  );
}
